const comments = [
  "My dude!",
  "Man I can't believe you said that to her",
  "Yep, sometimes that happens and there's nothing you can do about it",
  "My mother in law told me about that, lots of people are saying it right now",
  "Come on man, we talked about this",
  "I don't know but did you hear that a lot of crabs are barely related to each other? Just hearing about this",
  "Whoa, whoa, don't say anything too inflammatory on the internet, people will remember it forever",
  "I can't believe how crazy halloween was!",
  "Man my house is messy right now",
  "Yo somebody come help me move my couch :'D",
  "Hey guys I'm new here, can you tell me how to leave a reaction on a thought",
  "You ever think about how if you throw a rock in a lake, you're likely the last human to ever touch it",
  "Why do cities make benches that are so uncomfortable?",
  "Who here has a strong opinion on slime mold; trying to see something",
  "Did you know that trees are really, really bad at using light for energy",
  "If there's a bridge and you fill its river with dry dirt; is it still a bridge?",
  "I wonder if Tom Hanks ever went back out there to find Wilson",
];
module.exports = comments;
